import type { Metadata } from "next";
import {Inter} from 'next/font/google'
// import localFont from "next/font/local";
import "./globals.css";

import {cn} from "@/lib/utils"
import { QueryProvider } from "@/components/query-provider";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Collaborate X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        {/* QueryProvider for better typecheck in routes & typecheck request */}
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
